import type { NextPage } from "next";
import Head from "next/head";
import Hero from "../components/Hero";
import OurTeam from "../components/OurTeam";
import Partners from "../components/Partners";
import Products from "../components/Products";
import Services from "../components/Services";
import Offers from "../components/Offers";
import Layout from "../components/Layout";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Loomi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Hero />
        <Services />
        <Products />
        <Partners />
        <Offers />
        <OurTeam />
      </Layout>
    </div>
  );
};

export default Home;
